identifier_name:
  excluded:
    - up
    - id
    - x
    - y
    - dx
    - dy
    - App
trailing_comma:
  mandatory_comma: true
excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - "**/DerivedData"
  - "**/.build"
