# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 15.3.0 # indicate your selected version of Xcode
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run: brew install xcbeautify
      - macos/preboot-simulator:
          version: "17.4"
          platform: "iOS"
          device: "iPhone 15"
      - run:
          name: Run Unit Tests
          command: set -o pipefail && xcodebuild -project Client/Client.xcodeproj -scheme Client test -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' | xcbeautify --report junit
      - store_test_results:
          path: build/reports/junit.xml
  test-parallel: # your job name
    macos:
      xcode: 15.3.0 # indicate your selected version of Xcode
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run: brew install xcbeautify
      - macos/preboot-simulator:
          version: "17.4"
          platform: "iOS"
          device: "iPhone 15"
      - run:
          name: Run Unit Tests
          command: NSUnbufferedIO=YES xcodebuild -project Client/Client.xcodeproj -scheme "ClientTests - Parallel" test -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' -parallel-testing-enabled YES -parallel-testing-worker-count 2 2>&1 | xcbeautify --report junit
      - store_test_results:
          path: build/reports/junit.xml
workflows:
  tests:
    jobs:
      - test
      - test-parallel