name: Generate Intel Server App for fast catch

on:
  workflow_dispatch:

jobs:
  parallel-testing:
    name: Generate intel app
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode version
        run: sudo xcode-select -switch '/Applications/Xcode_14.3.1.app'
      - name: Generate zip
        run: |
          generate-zip.sh
      - name: Archive cli logs
        uses: actions/upload-artifact@v3
        with:
          name: PreBuildIntelApp.zip
          path: Lib/Sources/UIUnitTestCLI/Resources/PreBuild.zip
