name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mint
        run: |
          brew install mint
      - name: Build & Test
        env:
          scheme: 'Client'
          platform: ${{ 'iOS Simulator' }}
        run: |
          # Get iPhone 14 iOS 16.2 UUID
          deviceUUID=`xcrun simctl list | sed '1,/-- iOS 16.2 --/d' | grep "iPhone 14" | head -1 | grep -E '([0-9A-F]{4,}-?)+' -o`
          # Start simulator before building
          xcrun simctl bootstatus "$deviceUUID" -b       
          #run UIUnitTest server
          mint run BrunoMazzo/UIUnitTest@main start-server-command --device-identifier $deviceUUID
          xcodebuild -project Client/Client.xcodeproj  -scheme Client -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,id=$deviceUUID' test
