name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Test
        env:
          scheme: 'Client'
          platform: ${{ 'iOS Simulator' }}
        run: |
          # Get iPhone 14 iOS 16.2 UUID
          deviceUUID=`xcrun simctl list | sed '1,/-- iOS 16.2 --/d' | grep "iPhone 14" | head -1 | grep -E '([0-9A-F]{4,}-?)+' -o`
          # Start simulator before building
          xcrun simctl bootstatus "$deviceUUID" -b       
          ./run-all-tests.sh
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
