name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mint
        run: |
          brew install mint
      - name: Build & Test
        env:
          scheme: 'Client'
          platform: ${{ 'iOS Simulator' }}
        run: |
          # Debug device list
          xcrun xctrace list devices

          # Get iPhone 14 iOS 16.2 UUID
          deviceUUID=`xcrun xctrace list devices 2>&1 | grep -oE '([[A-F0-9]{4}\-?)*' | head -1`

          echo $deviceUUID

          #run UIUnitTest server
          mint run BrunoMazzo/UIUnitTest@main start-server-command --device-identifier $deviceUUID
          xcodebuild -project Client/Client.xcodeproj  -scheme Client -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,id=$deviceUUID' test
