name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mint
        run: |
          brew install mint
      - name: Build & Test
        env:
          scheme: 'Client'
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild -project Client/Client.xcodeproj  -scheme Client -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' test
