name: iOS tests

on:
  push:
    branches: [ "main", "parallel-testing", "swift-testing" ]
  pull_request:

jobs:
  parallel-testing:
    name: Cloned simulator
    runs-on: macos-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Test
        run: |
          make test-parallel
      - name: Archive Tests-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: Client/.uiUnitTest/Logs
          name: UIUnitTestLogs
      - name: Compress XCResult
        run: tar -cvzf test-result.tar test-result.xcresult
      - name: Archive Tests-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: test-result.tar
          name: Tests-results
      - name: Archive Tests-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: build/reports/junit.xml
          name: jUnit-tests-results.xml

      #   with:
      #     name: cli-logs-clone-simulator
      #     path: Client/logfile.txt
  single-device-testing:
    name: Normal simulator
    runs-on: macos-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Test
        timeout-minutes: 20
        run: |
          #run UIUnitTest server
          make test
      # - name: Archive cli logs
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: cli-logs-single-simulator
      #     path: Client/logfile.txt
